# Generated by Django 2.2.2 on 2020-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_versionmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionmanager',
            name='version',
            field=models.CharField(default='v1.0', max_length=10),
        ),
    ]
