# Generated by Django 2.2.2 on 2020-01-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20200126_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VersionManager',
        ),
    ]
